### PR TITLE
Set tcp socket to null for errors and attempt to create new socket un…

### LINKED ISSUE #1: Connection fails when VLC takes too long to start up
This is because connection will try and fail before vlc starts

### PR DESCRIPTION
**Pull request by johmarchetti**
…til successful

### CODE REVIEW

**Comment by Andrewskev** [comment]
did you change something?

**Comment by johmarchetti** [comment]
Darn right I did. Fixed the unable to reconnect problem if we lose connection during runtime, and the fix also allows the socket to keep trying to connect if vlc opens too late

**Comment by Andrewskev** [comment]
WOW

**Comment by Andrewskev** [comment]
How do I get your adjusted code?

**Pull request merged**
